name: deployment-pipeline
run-name: ${{ github.actor }} pushed a commit
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          check-latest: true
      - name: Install dependencies
        run: go get .
      - name: Build
        run: scripts/build-gotest.sh
      - name: Lint
        run: scripts/lint-gotest.sh
      - name: Run tests
        run: scripts/test-gotest.sh
      - name: Validate examples
        run: scripts/validate-examples.sh

